# Generated by Django 5.0.2 on 2024-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=20)),
                ("sub_category", models.CharField(max_length=20)),
                ("question_title", models.CharField(max_length=255)),
                ("question_text", models.TextField()),
            ],
        ),
    ]
