# Generated by Django 5.0.2 on 2024-07-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_text",
        ),
    ]
