# Generated by Django 5.0.2 on 2024-08-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_remove_question_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="file_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
