# Generated by Django 5.0.2 on 2024-08-26 20:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question", "0003_question_file_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogMockInterview",
            fields=[
                (
                    "log_mock_interview_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("submit_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("intent", models.BooleanField(default=False)),
                ("potential", models.BooleanField(default=False)),
                ("logical", models.BooleanField(default=False)),
                ("personality", models.BooleanField(default=False)),
                ("expertise", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockInterviewAnswer",
            fields=[
                (
                    "mock_interview_answer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "question_num",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("answer", models.TextField()),
                ("feedback", models.TextField()),
                (
                    "log_mock_interview_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_mock_interview.logmockinterview",
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question.question",
                    ),
                ),
            ],
        ),
    ]
