# Generated by Django 5.0.2 on 2024-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_mock_interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockinterviewanswer",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
