# Generated by Django 5.0.2 on 2024-10-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_mock_interview", "0002_alter_mockinterviewanswer_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockinterviewanswer",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
