# Generated by Django 5.1.2 on 2024-11-05 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogMockInterview",
            fields=[
                (
                    "log_mock_interview_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("submit_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "relevance",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "clarity",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "depth",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "logic",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(15),
                        ],
                    ),
                ),
                (
                    "awareness",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "log_mock_interview",
            },
        ),
        migrations.CreateModel(
            name="MockInterviewAnswer",
            fields=[
                (
                    "mock_interview_answer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "question_num",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("answer", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "mock_interview_answer",
            },
        ),
    ]
