# Generated by Django 5.1.2 on 2024-11-05 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_mock_interview", "0001_initial"),
        ("question", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logmockinterview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mockinterviewanswer",
            name="log_mock_interview_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="log_mock_interview.logmockinterview",
            ),
        ),
        migrations.AddField(
            model_name="mockinterviewanswer",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="question.question"
            ),
        ),
    ]
