# Generated by Django 5.0.2 on 2024-07-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseAnswer",
            fields=[
                (
                    "exercise_answer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("answer", models.TextField()),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.TextField()),
                ("feedback_improvement", models.TextField()),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question.question",
                    ),
                ),
            ],
        ),
    ]
