# Generated by Django 5.1.2 on 2024-11-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=20)),
                ("sub_category", models.CharField(max_length=20)),
                ("question_title", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
            ],
        ),
    ]
