# Generated by Django 5.0.2 on 2024-07-21 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="quota",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MaxValueValidator(50)]
            ),
        ),
    ]
